name: Test Suite

# Only triggers on pushes/PRs to master
on:
    pull_request:
        branches:
            - master
    push:
        branches:
            - master

jobs:
    test:
        name: CI
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, windows-latest]
                dc: [dmd-latest, ldc-latest, ldc-1.15.0]
                arch: [x86_64]
                include:
                    - {os: windows-latest, dc: ldc-latest, arch: x86}

        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4

            - name: Install D compiler
              uses: dlang-community/setup-dlang@v2
              with:
                  compiler: ${{ matrix.dc }}

            - name: Run tests
              shell: bash
              run: dub test :engine -a ${{matrix.arch}}
    testsuite:
        name: Test262
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                dc: [ldc-latest]

        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4

            - name: Install D compiler
              uses: dlang-community/setup-dlang@v2
              with:
                  compiler: ${{matrix.dc}}

            - name: Run tests
              shell: bash
              run: ./run-test262.sh

            - name: Upload log
              uses: actions/upload-artifact@v3
              if: always()
              with:
                name: runtest262 log
                path: dmdscript-test262.log
